### ISSUE TITLE
passing an Array to a trigger fails

### ISSUE THREAD

**Issue by joeyh** [Copilot-Language/copilot-c99#19]
I wanted to trigger Serial.write on an Arduino, so I passed an Array 4 Int8 to a trigger. The compilation failed:

demo.hs: src/Copilot/Compile/C99/Translate.hs:(113,14)-(124,23): Non-exhaustive patterns in case

Sure enough, the constty function misses Array (and also Struct).

I think this would be a useful facility to have, to be able to log from copilot.

copilot-c99-3.1

**Comment by fdedden** [comment]
Thanks reporting your problem. This was a known problem (https://github.com/Copilot-Language/copilot-c99/issues/13), and has already been fixed with the 3.1.1 release of copilot-c99. You might have already found this out in the meantime, but if not please install the latest version.

When installed through cabal, this can be done by running:
```
cabal install --upgrade-dependencies copilot
```

Please let me know if this solves your problem.
